### ISSUE TITLE
flush chunkmeta more often

### ISSUE THREAD

**Issue by Gjum** [CivClassic/CivModCore#110]
currently only flushes changes some time after chunk unload, which often only happens on server shutdown, causing loss of hours of data when the server crashes (as happened a few times already)

flushing every 30min/5min/whatever would make crashes less painful, and possibly also shorten shutdown/restart times

shadowtrot said:
> it would be better to save async to cut main thread load, but for that it needs updated to be safe to do that async
> currently it synchronizes on the input and output queues and the chunkcoord when unloading to make sure main thread doesn't interfere

**Comment by wingzero54** [comment]
Duplicate to #43

**Comment by Gjum** [comment]
ah didn't see that when looking for similar issues. gonna move over the info and close this one
