### ISSUE TITLE
ContentAligners#getCentered in order misaligns multiples of row length

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/CivModCore#32]
https://i.imgur.com/u9EfiGO.png

https://github.com/CivClassic/CivModCore/blob/master/src/main/java/vg/civcraft/mc/civmodcore/inventorygui/components/ContentAligners.java#L23

**Comment by Diet-Cola** [comment]
[Attempted fix here](https://github.com/DevotedMC/CivModCore/pull/40), In need of review since I'm getting the intended effects working in test but its also 8am and I might of done something dumb

**Comment by Diet-Cola** [comment]
![image](https://user-images.githubusercontent.com/12645603/109616812-87fa3a80-7b2d-11eb-9dce-d16ab77b8e42.png)

**Comment by wingzero54** [comment]
Fixed by Diet
