### ISSUE TITLE
Anvil prompts

### ISSUE THREAD

**Issue by Protonull** [CivClassic/CivModCore#42]
Currently CivModCore offers a utility where you can prompt a player for input, however this is chat based and doesn't expire, and you need to enter a special value to exit out of the prompt. I think https://github.com/WesJD/AnvilGUI has the right idea. I'm not necessarily saying that chat prompts should be refactored, but I adding this as an option, whether that means adding the plugin or implementing our own version. It means for example that exiting the prompt is as easy as closing the inventory. Thoughts?

**Comment by Maxopoly** [comment]
Sounds cool, are anvils character limited?

**Comment by Protonull** [comment]
[Seems so](https://minecraft.gamepedia.com/Anvil#:~:text=The%20maximum%20length%20for%20renaming,before%20it%20can%20be%20used.)

**Comment by Maxopoly** [comment]
Is there any good reason why we wouldnt just use that existing AnvilGUI over rebuilding it?

**Comment by Protonull** [comment]
Figured it'd be considered dependency creep
