### ISSUE TITLE
ItemMap Lore not matching

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/CivModCore#50]
![](https://cdn.discordapp.com/attachments/612456224960806941/739657082579714109/Screenshot_from_2020-08-03_03-28-21.png)

Top is a lore item made in 1.16, bottom one made in 1.14

Lore does not match and thus FM does not work.

Can we fix this in the ItemMap matching methods? Do we want some kind of auto conversion?

**Comment by Protonull** [comment]
Relevant: https://github.com/PaperMC/Paper/issues/3852

**Comment by Protonull** [comment]
In the mean time, I'll modify `ItemAPI.areItemsSimilar(lhs, rhs)` to take this issue into account. I can't really do more than that because even if PaperMC solves the structure issue, it wouldn't solve the matching issue for any item created since the update.

**Comment by Maxopoly** [comment]
I think we should just do a full conversion, working on that

**Comment by Maxopoly** [comment]
Fixed in https://github.com/CivClassic/SimpleAdminHacks/commit/6dfd311157fc03da5ab93c35909714c66b380bdc
