### ISSUE TITLE
Scoreboard filled with spam which prevents player login

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/CivModCore#63]
This was previously ignored because it seemed like a one-off issue, but more players have reported their scoreboard getting filled with random locations coords (likely snitches?). This prevents some players from being able to log in to the server because of the load on their client. HenryDraton reportedly was only able to resolve by joining on 1.16 and typing /config, which resolved the issue. 

I'm unsure of whether this is primarily a ViaVersion issue, but Henry was unable to load into the server on 1.16 even until he typed /config (does that reload or something?)

**Comment by Maxopoly** [comment]
ViaVersion issue/ Older client in general. It's not snitches, but the thing showing your current location in the sidebar. If people have issues with it they can turn it off or use 1.16.1, we don't provide support to older versions.
